posts/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import post_list, post_delete, post_detail, post_create, post_update

urlpatterns = [
    url(r'^$',post_list,name='list'),
    url(r'^create$',post_create,name='create'),
    url(r'^(?P<id>\d+)/$',post_detail,name="detail"),
    url(r'^(?P<id>\d+)/edit$',post_update, name="update"),
    url(r'^list$',post_list,name='list'),
    url(r'^(?P<id>\d+)/delete',post_delete,name="delete")
]

trydjango19/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^posts/',include("posts.urls" ,namespace='posts'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

posts/models.py
from __future__ import unicode_literals

from django.core.urlresolvers import reverse
from django.db import models

# Create your models here.
class Posts(models.Model):
    title=models.CharField(max_length=20)
    content=models.TextField()
    updated=models.DateTimeField(auto_now=True,auto_now_add=False)
    timestamp=models.DateTimeField(auto_now=False,auto_now_add=True)

    def __unicode__(self):
        return self.title

    def __str__(self):
        return  self.title

posts/forms.py
from django import forms

from .models import Posts

class PostForm(forms.ModelForm):
    class Meta:
        model= Posts
        fields=[
            "title",
            "content"
        ]

posts/views.py
from django.core.urlresolvers import reverse
from django.shortcuts import render,get_object_or_404,HttpResponseRedirect, redirect
from django.http import HttpResponse

from .models import Posts
from .forms import PostForm


def post_create(request):
    forms= PostForm(request.POST or None)
    if forms.is_valid():
        instance=forms.save(commit=False)
        instance.save()
        return HttpResponseRedirect(reverse("posts:detail", kwargs={"id": instance.id}))
    context={
        "forms":forms
    }
    return render(request, "post_create.html", context)

def post_detail(request,id):
   # queryset = Posts.objects.get(id=id)
    queryset = get_object_or_404(Posts,id=id)
    context = {
        "object_list": queryset
    }
    return render(request,"post_detail.html",context)

def post_list(request):
    queryset = Posts.objects.all()
    context={
        "object_list" :queryset
    }
    return render(request,"posts_list.html",context)

def post_delete(request,id):
    queryset = get_object_or_404(Posts,id=id)
    queryset.delete()
    return redirect("posts:list")


def post_update(request,id):
   # queryset = Posts.objects.get(id=id)
    queryset = get_object_or_404(Posts,id=id)
    forms = PostForm(request.POST or None,instance=queryset)
    if forms.is_valid():
        instance = forms.save(commit=False)
        instance.save()
        print "hello"
        return HttpResponseRedirect(reverse("posts:detail", kwargs={"id":id}))

    context = {
        "object_list": queryset,
        "forms":forms
    }
    return render(request,"post_create.html",context)


# Create your views here.

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Trying Django</title>
    <link rel="stylesheet" href="../static/posts/css/base.css">
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
      integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
      integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

</head>
<body>
<div class="container">
    {% block content %}

    {% endblock content %}
</div>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous">
</script>

</body>
</html>

templates/post_create.html
{% extends "base.html" %}

{% block content %}

<h1>FORM</h1>
<form method="POST">{% csrf_token %}
{{forms.as_p}}
 <input type="submit"  value="Create Post">
</form>

{% endblock content %}

templates/post_detail.html
{% extends "base.html" %}

{% block content %}
    <h1>{{object_list.title}}</h1>
    <h4>{{object_list.content}}</h4>
    <a href="{% url 'posts:update' id=object_list.id  %}"><button> EDIT </button></a>
    <a href="{% url 'posts:delete' id=object_list.id  %}"><button> Delete </button></a>

{% endblock content %}

templates/posts_list.html
{% extends "base.html" %}

{% block content %}

{% for obj in object_list %}
    <a href="{% url 'posts:detail' id=obj.id  %}"><h1> {{obj.title}}</h1></a>
    <h4>{{obj.content}}</h4>
    <h4>{{obj.timestamp}}</h4>
    <h4>{{obj.updated}}</h4>
    <a href="{% url 'posts:delete' id=obj.id  %}"><button> Delete </button></a>
{% endfor %}

{% endblock content %}